mics = 1;
order = 20;
winsize = 1000;
mscale = 0.001;
mshift = 0.999;
[vec, lambdas, f, z, w, r] = modesynth(mics, order, winsize, mscale, mshift);
[evec, eval] = modesolver(vec, mics, order, winsize-order-1);
enorm = ones(order*mics, 1) * evec(end, :);
evec_n = evec ./ enorm;
c = modal_regression(vec, evec_n, eval, mics, order);
fhat = evec_n * inverse_filter(c, eval);
fhat = real(fhat(end-mics+1:end, 1:end-order));
plot([fhat(:, 1:50); -f(1, 1+order:50+order)]');
