mics = 1;
order = 4;
winsize = 1000;
mscale = 0.001;
mshift = 0.999;
[vec, lambdas, f, z, w, r] = modesynth(mics, order, winsize, mscale, mshift);
[evec, eval] = modesolver(vec, mics, order, winsize-order-1);
enorm = ones(order*mics, 1) * evec(end, :);
evec_n = evec ./ enorm;
enorm0 = ones(order*mics, 1) * evec(1, :);
evec_n0 = evec ./ enorm0;
cn0 = modal_regression(vec, evec_n0, eval, mics, order);
cn = modal_regression(vec, evec_n, eval, mics, order);
c = modal_regression(vec, evec, eval, mics, order);
fhat_n = inverse_filter(cn, eval);
fhat = inverse_filter(c, eval);
rhat = evec_n * fhat;
rhat = real(rhat(end-mics+1:end, 1:end-order));
subplot(2, 1, 1);
plot(rhat(:, 1:50)');
subplot(2, 1, 2);
plot(f(:, 1+order:50+order)');
